version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mydb
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: products_db
      MYSQL_USER: sebozo
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: